export PATH="$HOME/.local/bin:$PATH"
rm -rf /var/lib/dpkg/lock
rm -rf /var/cache/debconf/*.*
rm -rf /var/lib/apt/lists/lock
rm -rf /var/cache/apt/archives/lock

pip install wheel
pip install colorama
pip install pyproject
pip install pyproject.toml
pip install pypandoc
pip install docker
pip install pycore
pip install pyopenssl
pip install pychroot
pip install rsa
pip install argparse
pip install async_generator
pip install asyncio
pip install beautifulsoup4
pip install bs4
pip install certifi
pip install cffi
pip install chardet
pip install faker
pip install fake-headers
pip install fake-useragent
pip install html5lib
pip install idna
pip install mechanize
pip install pyaes
pip install pycparser
pip install PySocks
pip install pytz
pip install pyasn1
pip install mock
pip install requests
pip install selenium
pip install six
pip install soupsieve
pip install telethon
pip install undetected-chromedriver
pip install urllib3
pip install webencodings
pip install golang
pip install nodejs
pip install ruby
pip install setuptools-rust
pip install touch
pip install npyscreen
pip install fake-useragent
pip install lolcat
pip install requests-toolbelt
pip install click
pip install pysqlite3
pip install kiwi
pip install faucetpy
pip install decoder
pip install btc
pip install bitcoin
pip install wh
pip install cs
pip install hacks
pip install data_hacks
pip install hacking
pip install requests-skip-verify
pip install pip-install-privates
pip install verify
pip install adder
pip install unicode
pip install unidecode
pip install captcha-harvester
pip install cheat
pip install pre-commit-hooks
pip install git-hooks
pip install autoclicker
pip install proxy.py
pip install proxypypi
pip install babel
pip install yarl
pip install pycurl
pip install status
pip install kiwisolver
pip install captcha-solver
pip install fire
pip install psutil
pip install decorator
pip install python-bitcoinlib
pip install litecoin-utils
pip install litecoin-script
pip install litecoin
pip install litecoin-requests
pip install lxml
pip install python-dogecoin
pip install doge
pip install bip-utils
pip install coinmarketcap
pip install cryptos
pip install pywallet
pip install doge-scan
pip install DogechainApi
pip install troncli
pip install tronpy
pip install ethereum
pip install repository-miner
pip install python-core
pip install coreapi
pip install digibyte
pip install digibyte-scrypt
pip install wax
pip install blockchain
pip install easy-blockchain
pip install captchasolver
pip install mpmath
pip install pycryptodome
pip install scrypt
pip install pymongo
pip install lru-dict
pip install websockets
pip install z3
pip install solver
pip install rust
pip install bitcoinlib
pip install pyethereum
pip install wget
pip install torch
pip install base58
pip install ecdsa
pip install requests
pip install PySimpleGUI
pip install pyfiglet
pip install make
pip install cmake
pip install bitcoin-python3
pip install yubico-bitcoin
pip install bitcoin-forecast
pip install bitcoin-client
pip install bitcoin-keygen
pip install polyglot-bitcoin
pip install dj-bitcoin
pip install django-bitcoin
pip install quantworks-bitcoin
pip install bitcoin-utils
pip install bitcoin-xyz
pip install sqlalchemy-bitcoin
pip install bitcoin.sh
pip install bitcoin-requests
pip install bitcoin-graph
pip install bitcoin-rpc-client
pip install bitcoin-toolkit
pip install python-bitcoin
pip install bitcoin-deposit-worker
pip install bitcoin-spv-py
pip install bitcoin-coin-selection
pip install bitcaviar
pip install googleparser
pip install coinbridge
pip install bitcoins
pip install bitcoincli
pip install bitcoinrpc
pip install darth
pip install Base-69
pip install base64
pip install base2048
pip install pybase64
pip install SR29
pip install Litecoin
pip install litecoin-requests
pip install litecoin_scrypt
pip install litecoin-utils
pip install python-litecointx
pip install cryptoassets.core
pip install tinycoinlib
pip install cryptos
pip install ltc_scrypt
pip install pycryptotools
pip install pycointools
pip install moonwalking
pip install reCaptchaBypasser
pip install piped-api
pip install pykeygen
pip install bitcoin-etl
pip install kiwi-blockchain
pip install blockchain-wiki
pip install blockchain-COHEN
pip install blockchain-myananta
pip install blockchain-exploration
pip install simple-blockchain
pip install blockchain-dbt
pip install gorgon-blockchain
pip install blockchain-metrics
pip install blockchain-parser
pip install blockchain-etl-common
pip install milian-blockchain-sdk
pip install python-blockchain-explorer
pip install blockchain-COHEN-DA
pip install python-blockchain-api
pip install p2p-grpc-blockchain
pip install blockchain-etl-common-instrumented
pip install cert-schema_pastday
pip install blockchainpy
pip install bpl-api
pip install bitblock
pip install blackduck-c-cpp
pip install block
pip install pool
pip install aws-crypto
pip install torch-crypto
pip install virgil-crypto
pip install crypto-tools
pip install crypto-sim
pip install etaf-crypto
pip install crypto-licensing
pip install cave_miner
pip install crypt-dir
pip install crypt4gh
pip install py2crypt
pip install sha512-crypt
pip install Cryptem
pip install PySMT
pip install mqt.qusat
pip install ProcessScheduler
pip install pydelta
pip install pylambda
pip install bravo1996
pip install py2py
pip install py416
pip install networksdb
pip install mbd-pay
pip install bycore
pip install bep20
pip install web3-wrapped-contract
pip install Products.MeetingBEP
pip install pycache3
pip install pycaches
pip install pycached
pip install python-sat
pip install nimbus-sat
pip install py-aiger-sat
pip install z3-solver-crosshair
pip install deal-solver
pip install z3-solver-mythril
pip install z3-solver==4.4.2.1
pip install z3-solver==4.4.2.1.post1
pip install z3-solver==4.5.1.0
pip install blockchain-etl
pip install polygon-etl
pip install ethereum-etl
pip install cryptodatapy
pip install avalanche-etl
pip install solana-etl
pip install tezos-etl
pip install cosmos-etl
pip install bitcoin-etl
pip install bsc-etl
pip install polygon
pip install z4-solver

apt-get update
